######################################################################
# Automatically generated by qmake (2.01a) wt. sty 7 13:59:40 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += cell.h game.h mainwindow.h
FORMS += form.ui mainwindow.ui
SOURCES += cell.cpp game.cpp main.cpp mainwindow.cpp
